import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from app.db import SessionLocal, engine
from app.models import Job, Profile, User
from app.security import hash_password
from app.demo import ensure_demo_resume

db=SessionLocal()
try:
    demo_email="asha.verma@example.com"
    user=db.query(User).filter(User.email==demo_email).first()
    if not user:
        user=User(email=demo_email,name="Asha Verma",password_hash=hash_password("ApplyEase123!")); db.add(user); db.flush(); db.add(Profile(user_id=user.id,data={"name":"Asha Verma","email":demo_email,"phone":"+91 98765 43210","education":"B.Sc. Statistics · 2025","skills":"Excel · SQL · Communication · Research","experience":"","resume":"Asha_Verma_Resume.pdf"}))
    jobs=[
      {"id":"acme-data","title":"Data Analyst","company":"Acme Technologies","location":"Mumbai · Hybrid","type":"Full-time","summary":"Turn business data into clear reports and practical insights for product and operations teams.","original_text":"Data Analyst — Acme Technologies\nLocation: Mumbai · Hybrid\nType: Full-time\n\nThe Data Analyst will turn business data into clear reports and practical insights for product and operations teams. Responsibilities include analyzing operational datasets, building recurring reports and dashboards, and partnering with business teams to explain findings. Required: 2+ years working with data, SQL, and Excel or spreadsheet analysis. Preferred: Python and experience with dashboards. Application process: Resume, application questions, short recruiter call. Deadline: Not stated.","skills":["SQL","Excel","Data visualization","Python"],"required":["2+ years working with data","SQL","Excel or spreadsheet analysis"],"preferred":["Python","Experience with dashboards"],"responsibilities":["Analyze operational datasets","Build recurring reports and dashboards","Partner with business teams to explain findings"],"process":["Resume","Application questions","Short recruiter call"],"deadline":"Not stated","source":"Company job description","apply_mode":"partner"},
      {"id":"northstar-ux","title":"UX Research Intern","company":"Northstar Labs","location":"Mumbai · Remote","type":"Internship","summary":"Support user research, synthesize qualitative findings and help product teams make evidence-informed decisions.","original_text":"UX Research Intern — Northstar Labs\nLocation: Mumbai · Remote\nType: Internship\n\nSupport user research, synthesize qualitative findings and help product teams make evidence-informed decisions. Responsibilities include supporting interviews and usability studies, synthesizing notes into themes, and creating research readouts. Required: current student or recent graduate and strong written communication. Preferred: Figma and a prior research project. Application process: Resume, portfolio, application questions. Deadline: October 18, 2026.","skills":["Research","Figma","Interviewing","Writing"],"required":["Current student or recent graduate","Strong written communication"],"preferred":["Figma","Prior research project"],"responsibilities":["Support interviews and usability studies","Synthesize notes into themes","Create research readouts"],"process":["Resume","Portfolio","Application questions"],"deadline":"October 18, 2026","source":"Employer-submitted demo job","external_url":"https://example.com/employer-demo/northstar-ux","apply_mode":"external"},
      {"id":"orbit-support","title":"Customer Support Specialist","company":"Orbit Cloud","location":"Pune · Hybrid","type":"Full-time","summary":"Help customers solve product questions through clear communication, troubleshooting and thoughtful follow-up.","original_text":"Customer Support Specialist — Orbit Cloud\nLocation: Pune · Hybrid\nType: Full-time\n\nHelp customers solve product questions through clear communication, troubleshooting and thoughtful follow-up. Responsibilities include responding to customer questions, documenting recurring issues, and coordinating with product and engineering. Required: strong written communication and comfort with customer-facing work. Preferred: SaaS support experience and CRM familiarity. Application process: Resume, scenario questions, interview. Deadline: October 12, 2026.","skills":["Communication","Troubleshooting","CRM"],"required":["Strong written communication","Comfort with customer-facing work"],"preferred":["SaaS support experience","CRM familiarity"],"responsibilities":["Respond to customer questions","Document recurring issues","Coordinate with product and engineering"],"process":["Resume","Scenario questions","Interview"],"deadline":"October 12, 2026","source":"Public demo feed","external_url":"https://example.com/employer-demo/orbit-support","apply_mode":"external"}
    ]

    common=[
      {"key":"name","label":"What is your full name?","hint":"We will use this exactly as it appears on your application.","type":"text","required":True,"prefillKey":"name"},
      {"key":"email","label":"What email should the employer use?","hint":"Use an address you check regularly.","type":"email","required":True,"prefillKey":"email"}
    ]
    forms={
      "acme-data": common + [{"key":"phone","label":"What is your phone number?","hint":"Use a 10-digit number.","type":"tel","required":True,"prefillKey":"phone"},{"key":"resume","label":"Which resume should we use?","hint":"Upload your resume.","type":"file","required":True,"prefillKey":"resume","accept":".pdf,.doc,.docx"},{"key":"authorization","label":"Are you authorized to work in India?","hint":"Choose one answer.","type":"choice","required":True,"sensitive":True,"choices":["Yes","No","I am not sure","Prefer not to say"]},{"key":"why","label":"Why are you interested in this role?","hint":"Write in your own words.","type":"textarea","required":True,"validation":{"minLength":20}},{"key":"support","label":"Optional support request","hint":"Optional.","type":"note","required":False}],
      "northstar-ux": common + [{"key":"resume","label":"Which resume should we use?","hint":"Upload your resume.","type":"file","required":True,"prefillKey":"resume","accept":".pdf,.doc,.docx"},{"key":"studentStatus","label":"Are you currently a student or recent graduate?","hint":"Choose one.","type":"choice","required":True,"sensitive":True,"choices":["Current student","Recent graduate","Neither","Prefer not to say"]},{"key":"portfolio","label":"Where can the team view your portfolio?","hint":"Optional portfolio link.","type":"text","required":False},{"key":"why","label":"What interests you about UX research?","hint":"Mention a relevant project if useful.","type":"textarea","required":True,"validation":{"minLength":20}}],
      "orbit-support": common + [{"key":"phone","label":"What is your phone number?","hint":"Use the number you want a recruiter to call.","type":"tel","required":True,"prefillKey":"phone"},{"key":"resume","label":"Which resume should we use?","hint":"Upload your resume.","type":"file","required":True,"prefillKey":"resume","accept":".pdf,.doc,.docx"},{"key":"authorization","label":"Are you authorized to work in India?","hint":"Choose one answer.","type":"choice","required":True,"sensitive":True,"choices":["Yes","No","I am not sure","Prefer not to say"]},{"key":"scenario","label":"How would you respond to a frustrated customer?","hint":"Give a short example.","type":"textarea","required":True,"validation":{"minLength":20}},{"key":"support","label":"Optional note for the employer","hint":"Optional.","type":"note","required":False}]
    }
    for x in jobs:
        if not db.get(Job,x["id"]): db.add(Job(**x,form=forms[x["id"]]))
        else:
            existing=db.get(Job,x["id"]); existing.form=forms[x["id"]]; existing.external_url=x.get("external_url")
    db.commit()
    ensure_demo_resume(db)
finally: db.close()
